"""refactored nlg report codebase

Revision ID: 38a895d8d600
Revises: 84146a01839e
Create Date: 2024-10-28 07:44:46.606051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38a895d8d600'
down_revision: Union[str, None] = '84146a01839e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nlg_report', sa.Column('driver_profile_id', sa.BINARY(length=16), nullable=False))
    op.add_column('nlg_report', sa.Column('generated_at', sa.DateTime(), nullable=False))
    op.alter_column('nlg_report', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
    op.alter_column('nlg_report', 'report_text',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('nlg_report', 'synced',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_foreign_key(None, 'nlg_report', 'driver_profile', ['driver_profile_id'], ['driver_profile_id'])
    op.drop_column('nlg_report', 'date_range')
    op.drop_column('nlg_report', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nlg_report', sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('nlg_report', sa.Column('date_range', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'nlg_report', type_='foreignkey')
    op.alter_column('nlg_report', 'synced',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('nlg_report', 'report_text',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=False)
    op.alter_column('nlg_report', 'id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.drop_column('nlg_report', 'generated_at')
    op.drop_column('nlg_report', 'driver_profile_id')
    # ### end Alembic commands ###
