"""refactored embedding code

Revision ID: 84146a01839e
Revises: 4b58a4ecc8fa
Create Date: 2024-10-28 07:06:07.123148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84146a01839e'
down_revision: Union[str, None] = '4b58a4ecc8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('chunk_id', sa.BINARY(length=16), nullable=False),
    sa.Column('chunk_text', sa.String(length=255), nullable=False),
    sa.Column('embedding', sa.String(length=1024), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.drop_table('embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('chunk_id', sa.BINARY(length=16), nullable=False, comment='Unique identifier for each chunk of text.'),
    sa.Column('chunk_text', mysql.VARCHAR(length=5000), nullable=False, comment='The text content of the chunk.'),
    sa.Column('embedding', sa.BLOB(), nullable=False, comment='Serialized embedding vector for the chunk.'),
    sa.Column('source_type', mysql.VARCHAR(length=255), nullable=False, comment='The type of source (e.g., nat_dr_reg_law, ng_high_way_code).'),
    sa.Column('source_page', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='The page number for traceability.'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='The timestamp indicating when the embedding was created.'),
    sa.PrimaryKeyConstraint('chunk_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('embedding')
    # ### end Alembic commands ###
