"""Changed DrivingTips to DrivingTip

Revision ID: 8fa22ef11d8d
Revises: d35853966e69
Create Date: 2024-10-26 00:45:58.157430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa22ef11d8d'
down_revision: Union[str, None] = 'd35853966e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
