"""added driver_profile_id to unsafe_behaviour and did a backpopulate in driver_id

Revision ID: a281668694a0
Revises: 537b5697b6a3
Create Date: 2024-10-27 16:48:41.874689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a281668694a0'
down_revision: Union[str, None] = '537b5697b6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unsafe_behaviour', sa.Column('driver_profile_id', sa.BINARY(length=16), nullable=False))
    op.create_foreign_key(None, 'unsafe_behaviour', 'driver_profile', ['driver_profile_id'], ['driver_profile_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unsafe_behaviour', type_='foreignkey')
    op.drop_column('unsafe_behaviour', 'driver_profile_id')
    # ### end Alembic commands ###
