"""added synced column to ai_module_input

Revision ID: ad0f1d66a756
Revises: ef70aac5ee1c
Create Date: 2024-10-28 08:41:39.694169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0f1d66a756'
down_revision: Union[str, None] = 'ef70aac5ee1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_model_inputs', sa.Column('synced', sa.Boolean(), nullable=False))
    op.add_column('embedding', sa.Column('synced', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding', 'synced')
    op.drop_column('ai_model_inputs', 'synced')
    # ### end Alembic commands ###
