"""Fix TripData to Trip in  AIModelInput

Revision ID: c9e988bc5fce
Revises: 12b777688969
Create Date: 2024-10-26 00:35:12.061813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e988bc5fce'
down_revision: Union[str, None] = '12b777688969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
