"""Changed causes to cause in unsafe_behaviour

Revision ID: d35853966e69
Revises: feb5a90a7b01
Create Date: 2024-10-26 00:43:23.121058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35853966e69'
down_revision: Union[str, None] = 'feb5a90a7b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
