"""added synced column to unsafe_behaviours

Revision ID: ef70aac5ee1c
Revises: 38a895d8d600
Create Date: 2024-10-28 08:25:21.423433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef70aac5ee1c'
down_revision: Union[str, None] = '38a895d8d600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('causes', sa.Column('synced', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('causes', 'synced')
    # ### end Alembic commands ###
