"""Changed Trip to TripData

Revision ID: feb5a90a7b01
Revises: c9e988bc5fce
Create Date: 2024-10-26 00:41:07.588999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb5a90a7b01'
down_revision: Union[str, None] = 'c9e988bc5fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
