package com.uoa.safedriveafrica.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0D6E85)
val md_theme_light_onPrimary = Color(0xFFF1F9FE)
val md_theme_light_primaryContainer = Color(0xFFBEEAF2)
val md_theme_light_onPrimaryContainer = Color(0xFF002027)
val md_theme_light_secondary = Color(0xFFF6A400)
val md_theme_light_onSecondary = Color(0xFF2C1700)
val md_theme_light_secondaryContainer = Color(0xFFFFE0B2)
val md_theme_light_onSecondaryContainer = Color(0xFF402400)
val md_theme_light_background = Color(0xFFF6F7FF)
val md_theme_light_onBackground = Color(0xFF0A1B2C)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0A1B2C)
val md_theme_light_surfaceVariant = Color(0xFFDCE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF2F373F)
val md_theme_light_outline = Color(0xFF58707B)
val md_theme_light_surfaceTint = Color(0xFF0D6E85)
val md_theme_light_error = Color(0xFFb00020)
val md_theme_light_onError = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFF7AD7EF)
val md_theme_dark_onPrimary = Color(0xFF003640)
val md_theme_dark_primaryContainer = Color(0xFF004E60)
val md_theme_dark_onPrimaryContainer = Color(0xFFBEEAF2)
val md_theme_dark_secondary = Color(0xFFFFD180)
val md_theme_dark_onSecondary = Color(0xFF3E2300)
val md_theme_dark_secondaryContainer = Color(0xFF5E3600)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE0B2)
val md_theme_dark_background = Color(0xFF0A1D28)
val md_theme_dark_onBackground = Color(0xFFF0FBFF)
val md_theme_dark_surface = Color(0xFF111B23)
val md_theme_dark_onSurface = Color(0xFFE1E9F2)
val md_theme_dark_surfaceVariant = Color(0xFF1F2C36)
val md_theme_dark_onSurfaceVariant = Color(0xFFB9C4D0)
val md_theme_dark_outline = Color(0xFF8D99A6)
val md_theme_dark_surfaceTint = Color(0xFF7AD7EF)
val md_theme_dark_error = Color(0xFFCF6679)
val md_theme_dark_onError = Color(0xFF41000D)
